apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/REPLACEME/jarvis-rp:latest
  newName: ghcr.io/REPLACEME/jarvis-rp
  newTag: latest
