apiVersion: v1
kind: Service
metadata:
  name: ragemp-server
spec:
  selector:
    app: ragemp-server
  ports:
  - port: 22005
    targetPort: 22005
    protocol: UDP
    name: game
  - port: 22005
    targetPort: 22005
    protocol: TCP
    name: game
  - port: 22006
    targetPort: 22006
    protocol: TCP
    name: http
  type: LoadBalancer
