// <auto-generated />
using System;
using System.Collections.Generic;
using GameDb.Domain.Models;
using GameDb.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GameDb.Repository.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250508200412_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GameDb.Domain.Entities.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AddressName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.InfrastructureBuildingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("SocialClubId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("SocialClubId");

                    b.ToTable("InfrastructureBuildings");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.InventoryEntity", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<List<InventoryItemModel>>("Items")
                        .HasColumnType("jsonb");

                    b.Property<byte>("MaxWeight")
                        .HasColumnType("smallint");

                    b.Property<byte>("TotalWeight")
                        .HasColumnType("smallint");

                    b.HasKey("PlayerId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.ItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsUsable")
                        .HasColumnType("boolean");

                    b.Property<byte>("MaxStackSize")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte?>("OnlySlot")
                        .HasColumnType("smallint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<byte>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.PlayerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Cash")
                        .HasColumnType("bigint");

                    b.Property<byte>("HP")
                        .HasColumnType("smallint");

                    b.Property<byte>("Hunger")
                        .HasColumnType("smallint");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<long?>("SocialClubId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Stamina")
                        .HasColumnType("smallint");

                    b.Property<byte>("Thirst")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SocialClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.RealEstateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<byte>("MaxResidentCount")
                        .HasColumnType("smallint");

                    b.Property<byte>("MaxVehicleCount")
                        .HasColumnType("smallint");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("RealEstates");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.ResidenceEntity", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RealEstateId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "RealEstateId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("RealEstateId");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.SocialClubEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialClubs");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.VehicleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("NumberPlate")
                        .HasColumnType("text");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.InfrastructureBuildingEntity", b =>
                {
                    b.HasOne("GameDb.Domain.Entities.AddressEntity", "Address")
                        .WithOne()
                        .HasForeignKey("GameDb.Domain.Entities.InfrastructureBuildingEntity", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDb.Domain.Entities.SocialClubEntity", "SocialClub")
                        .WithMany()
                        .HasForeignKey("SocialClubId");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.InventoryEntity", b =>
                {
                    b.HasOne("GameDb.Domain.Entities.PlayerEntity", "Player")
                        .WithOne()
                        .HasForeignKey("GameDb.Domain.Entities.InventoryEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDb.Domain.Entities.PlayerEntity", b =>
                {
                    b.HasOne("GameDb.Domain.Entities.SocialClubEntity", "SocialClub")
                        .WithMany()
                        .HasForeignKey("SocialClubId");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.RealEstateEntity", b =>
                {
                    b.HasOne("GameDb.Domain.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDb.Domain.Entities.PlayerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("GameDb.Domain.Entities.ResidenceEntity", b =>
                {
                    b.HasOne("GameDb.Domain.Entities.PlayerEntity", "Player")
                        .WithOne()
                        .HasForeignKey("GameDb.Domain.Entities.ResidenceEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDb.Domain.Entities.RealEstateEntity", "RealEstate")
                        .WithMany()
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDb.Domain.Entities.VehicleEntity", b =>
                {
                    b.HasOne("GameDb.Domain.Entities.PlayerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
