name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase owner name
        id: lowercase_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM ubuntu:20.04

          # Prevent interactive prompts during package installation
          ENV DEBIAN_FRONTEND=noninteractive
          ENV TZ=UTC

          # Install dependencies
          RUN apt-get update && apt-get install -y \
              wget \
              unzip \
              libatomic1 \
              xz-utils \
              apt-transport-https \
              nano \
              && rm -rf /var/lib/apt/lists/*

          # Install .NET runtime
          RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
              && dpkg -i packages-microsoft-prod.deb \
              && apt-get update \
              && apt-get install -y dotnet-runtime-6.0 \
              && rm -rf /var/lib/apt/lists/*

          # Create directory for the server
          WORKDIR /ragemp-server

          # Download and extract RAGE MP server
          RUN wget https://cdn.rage.mp/lin/ragemp-srv.tar.gz \
              && tar -xzf ragemp-srv.tar.gz \
              && rm ragemp-srv.tar.gz \
              && chmod +x /ragemp-srv/ragemp-server \
              && /ragemp-srv/ragemp-server \
              && pkill ragemp-server || true

          # Copy your server files
          COPY client_packages/ /ragemp-srv/client_packages/
          COPY packages/ /ragemp-srv/packages/
          COPY maps/ /ragemp-srv/maps/
          COPY plugins/ /ragemp-srv/plugins/
          COPY conf.json /ragemp-srv/conf.json
          COPY dotnet/ /ragemp-srv/dotnet/

          # Expose necessary ports
          EXPOSE 22005/tcp 22005/udp 22006/tcp 22006/udp

          # Set working directory to the server location
          WORKDIR /ragemp-srv

          # Create a start script
          RUN echo '#!/bin/bash\n/ragemp-srv/ragemp-server' > /ragemp-srv/start.sh \
              && chmod +x /ragemp-srv/start.sh

          CMD ["/ragemp-srv/start.sh"]
          EOF

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/jarvis-rp:latest
            ghcr.io/${{ steps.lowercase_owner.outputs.owner }}/jarvis-rp:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max